AnyVisionltd/anv-ui-components

package-lock.json, package.json, src/components/__snapshots__/Storyshots.test.js.snap
=> Update anv icons version

src/components/Table/Selection/BulkAction/BulkAction.js, src/components/__snapshots__/Storyshots.test.js.snap
=> Table selection -> sub menu anchor fix

CHANGELOG.md, src/components/Tooltip/Tooltip.js, src/components/Tooltip/Tooltip.test.js, src/components/__snapshots__/Storyshots.test.js.snap
=> Add tooltip show prop

CHANGELOG.md, package.json, src/components/Tooltip/Tooltip.js, src/components/__snapshots__/Storyshots.test.js.snap
Change react event listener to native event listener 
Update react
=> Tooltip bug fix

.prettierignore, CHANGELOG.md, src/components/Button/Button.module.scss, src/components/SelectionGroup/SelectionGroup.js, src/components/SelectionGroup/SelectionGroup.module.scss, src/components/SelectionGroup/SelectionGroup.stories.js, src/components/SelectionGroup/SelectionGroupItem/SelectionGroupItem.js, src/components/SelectionGroup/SelectionGroupItem/SelectionGroupItem.module.scss, src/components/SelectionGroup/SelectionGroupItem/index.js, src/components/SelectionGroup/index.js, src/components/__snapshots__/Storyshots.test.js.snap, src/index.js, src/styles/mixin/ripple.scss
Add <SelectionGroup/> Component to storybook
=> SelectionGroup

.gitignore, src/components/SelectionGroup/SelectionGroup.js, src/components/SelectionGroup/SelectionGroup.test.js, src/components/SelectionGroup/SelectionGroupItem/SelectionGroupItem.js, src/components/SelectionGroup/SelectionGroupItem/SelectionGroupItem.module.scss
=> AB-6163 #time 0.3h add selectionGroup tests

.storybook/preview.js, src/components/Button/Button.stories.js, src/components/Checkbox/Checkbox.stories.js, src/components/Chip/Chip.stories.js, src/components/ChipsInput/ChipsInput.stories.js, src/components/Dialog/Dialog.stories.js, src/components/DialogWizard/DialogWizard.stories.js, src/components/IconButton/IconButton.stories.js, src/components/InfiniteList/InfiniteList.stories.js, src/components/InputBase/InputBase.stories.js, src/components/List/List.stories.js, src/components/Menu/Menu.stories.js, src/components/Radio/Radio.stories.js, src/components/SSF/SSF.stories.js, src/components/SelectionGroup/SelectionGroup.stories.js, src/components/SkeletonLoader/SkeletonLoader.stories.js, src/components/Snackbar/Snackbar.stories.js, src/components/Switch/Switch.stories.js, src/components/Table/stories/Basic.stories.js, src/components/Table/stories/InfiniteScroll.stories.js, src/components/TextField/TextField.stories.js, src/components/Tooltip/Tooltip.stories.js, src/components/__snapshots__/Storyshots.test.js.snap
Change storybook components sections
=> Storybook sections

CHANGELOG.md, src/components/Chip/Chip.js, src/components/DialogWizard/DialogWizard.js, src/components/Menu/Menu.js, src/components/Tooltip/Tooltip.module.scss, src/components/__snapshots__/Storyshots.test.js.snap
-Fixed Menu to not self open when controlled from outside 
-Added z-index to Tooltip component
-Changed last step of DialogWizard to trigger onFinish
=> Fixed chip and menu

.storybook/preview-body.html, src/components/TextField/TextField.js, src/components/TextField/TextField.module.scss, src/components/TextField/TextField.stories.js, src/components/__snapshots__/Storyshots.test.js.snap
=> Text field

src/components/Table/TableBody/TableRow/TableRow.js
=> Fix table menu

src/components/ChipsInput/ChipsInput.module.scss
=> box-size-to-chips-input

src/components/ChipsInput/ChipsInput.module.scss
=> Fix chip size

src/components/ChipsInput/ChipsInput.module.scss
=> Fix chips input helper text font

src/components/Dialog/Dialog.js, src/hooks/UseKeyDownListener/UseKeyDownListener.js
Add addEventListener to useKeyDown
=> dialog remove event listener when close

src/components/Table/TableBody/TableRow/TableRow.js, src/components/TextField/TextField.module.scss
=> remove textField width

src/components/InputBase/InputBase.js, src/components/__snapshots__/Storyshots.test.js.snap
=> Fix typo in tabIndex for InputBase

src/components/TextField/TextField.js
=> add-ref-to-view-textField

src/components/TextField/TextField.js
Reverts AnyVisionltd/anv-ui-components#232
=> Revert "add-ref-to-view-textField"

src/components/Table/TableHeader/TableHeader.js, src/components/Table/TableHeader/TableHeader.module.scss, src/components/Table/TableSSF/TableSSF.js, src/components/TextField/TextField.js, src/hooks/UseClickOutsideListener/UseClickOutsideListener.js
=> Added trailing icon to table header column

src/components/ChipsInput/ChipsInput.js, src/components/ChipsInput/ChipsInput.module.scss, src/components/ChipsInput/ChipsInput.stories.js, src/components/__snapshots__/Storyshots.test.js.snap
Add chips input controlled option
=> Controlled chips input

src/components/Portal/Portal.js
=> remove unmount

CHANGELOG.md, src/components/TextField/TextField.js
=> Fix text field cursor jump

CHANGELOG.md, src/components/ChipsInput/ChipsInput.js, src/components/SSF/SSF.js, src/components/SSF/SSF.test.js
=> fix-controlled-input-in-ChipsInput

src/components/TextField/TextField.js
=> fix-type-number-cursor-in-textField

CHANGELOG.md, src/components/ChipsInput/ChipsInput.js, src/components/SSF/SSF.js, src/components/SSF/SSF.test.js
This reverts commit 03087c7d749694bcefe95e9ba67c1f7b36a8910e.
=> Revert "fix-controlled-input-in-ChipsInput"

src/components/Menu/MenuItem/MenuItem.js, src/components/Menu/MenuItem/MenuItem.module.scss, src/components/TextField/TextField.stories.js
=> Ab 5425 menu item ellipsis and tooltip

CHANGELOG.md, package-lock.json, src/components/Table/ConfirmationDialog/ConfirmationDialog.js, src/components/Table/Selection/BulkAction/BulkAction.js, src/components/Table/Selection/Selection.js, src/components/Table/TableBody/TableBody.js, src/components/Table/TableBody/TableRow/TableRow.js, src/components/Table/stories/Basic.stories.js
fixed name and validation rules for a confirmation dialog content in Tble
added to storybook 
=> AB-5185 - confirmation dialog in table action should get JSX

src/components/Table/TableBody/TableRow/TableRow.js
support for dynamic confirmation dialog context
=> AB-5185 support for dynamic confirmation dialog context

package.json, src/index.js
=> Added progress component to exports

src/components/Progress/index.js
=> fixed export from index

src/components/Progress/Progress.module.scss
=> AB-7150 | add ability to change bar fill color

CHANGELOG.md, package-lock.json, src/components/DialogWizard/DialogWizard.js, src/components/DialogWizard/DialogWizard.stories.js, src/components/__snapshots__/Storyshots.test.js.snap, src/storybook/wizard.module.scss
=> Add classes prop to wizard

src/components/TextField/TextField.js, src/hooks/UseClickOutsideListener/UseClickOutsideListener.js, src/utils/index.js
=> fix-menu-close-in-textfield-options

CHANGELOG.md, src/components/Menu/Menu.js
=> AB-7227-dont-open-menu-if-controlled-from-outside

CHANGELOG.md, src/components/Tooltip/Tooltip.js, src/components/Tooltip/Tooltip.module.scss, src/components/Tooltip/Tooltip.stories.js, src/components/__snapshots__/Storyshots.test.js.snap
=> Added styles to tooltip child

src/storybook/Opacity/Opacity.module.scss, src/storybook/Opacity/Opacity.stories.mdx, src/storybook/Size/Size.module.scss, src/storybook/Size/Size.stories.mdx, src/storybook/Space/Space.module.scss, src/storybook/Space/Space.stories.mdx, src/storybook/Typography/Typography.stories.mdx
=> anv-ui-style guide to storybook

CHANGELOG.md, src/components/Portal/Portal.js
=> BTTRIBEV2-10063-remove-portal-on-unmount

CHANGELOG.md, package-lock.json, package.json
=> bump-version-90

CHANGELOG.md, src/components/Menu/Menu.js, src/components/TextField/TextField.js
=> Bttribev2 10370 textfield null check and portal

CHANGELOG.md, src/components/RangeSlider/RangeSlider.js, src/components/RangeSlider/RangeSlider.module.scss, src/components/RangeSlider/RangeSlider.stories.js, src/components/RangeSlider/RangeSlider.test.js, src/components/RangeSlider/index.js, src/components/__snapshots__/Storyshots.test.js.snap, src/index.js, src/utils/enums/keymap.js
I did a range slider component. The slider's elements are range input, tooltip to show the current value / current hovered value of the slider, and min/ max labels.
The slider get min, max, value, onChange, step, disabled, width and isToggleTooltip as props, if not given it gets the default.
Other props can be added like className, style.
Run storybook and checkout the examples, the component's functions and helpers are documented so it will be easier to understand the functions and calculations
=> Bttribev2 10270 range slider

CHANGELOG.md, src/components/Menu/Menu.js, src/components/Menu/Menu.test.js, src/components/Portal/Portal.js, src/components/Table/TableBody/TableRow/TableRow.js, src/components/__snapshots__/Storyshots.test.js.snap, src/utils/index.js
User could not click on options in table items, so the bug was fixed by generating random id for menu component, conditionally render it (  only if it supposed to be open i.e user clicked ) and remove the menu from the dom when menu is closed.
4 more tests added to check if initially menu exists / doesn't exist , if it's removed after rerendering with new props and if user clicks outside the menu
Test in storybook, and when merged in BT camera settings page
- [] run test
=> Bttribev2 9942 multiple items in table

src/components/DatePicker/DatePicker.js, src/components/DatePicker/DatePicker.stories.js, src/components/DatePicker/DatePicker.test.js
Added defaultDate in DatePicker
=> Date picker test update

src/components/RangeSlider/RangeSlider.js
=> Add prop range slider

package-lock.json, rollup.config.js, src/components/DatePicker/DatePicker.js, src/components/DatePicker/DatePicker.stories.js, src/components/DatePicker/index.js, src/components/__snapshots__/Storyshots.test.js.snap
=> BTTRIBEV2-10399/BTTRIBEV2-10473: DatePicker fix

rollup.config.js
=> BTTRIBEV2-10580: FIX add quotes

src/components/ProgressWithIndicator/ProgressWithIndicator.js
=> Added stopped in feedbackProps

src/components/Storyshots.test.js
=> Remove snapshots tests

package-lock.json, package.json
=> Change version to 108

src/components/Dropdown/Dropdown.js, src/components/Dropdown/Dropdown.module.scss
=> Added 2 changes for dropdown after checking it in bt

src/components/DatePicker/DatePicker.js, src/components/DatePicker/DatePicker.module.scss
=> BTTRIBEV2-10587: Date Picker icon- ADD background-color based on state

src/components/Dropdown/Dropdown.js, src/components/RangeSlider/DualThumb/DualThumb.js
1. Added the ability of DualThumb slider to change when value is changed from outside, like input that takes the same value.
2. Added canBeEmpty for Dropdown
3. Used usePrevious hook in Dropdown to measure if options / default values has really changed in useEffect and improve performance
Everything was checked in AddEditCamera in bt
=> Add canBeEmpty to Dropdown and update DualThumb slider when value is changed from outside

src/components/Menu/MenuItem/MenuItem.module.scss
=> updated the icon space in the menu item

src/components/Dropdown/Dropdown.js, src/utils/index.js
=> Fix dropdown clientBoundingRect

src/components/Tree/Tree.js, src/components/Tree/Tree.stories.js, src/components/Tree/useFlattenTreeData/useFlattenTreeData.js, src/components/Tree/useTreeVisibleData/useTreeVisibleData.js, src/components/Tree/utils/index.js
=> BTTRIBEV2-11234- Bulk expand and bulk select

package-lock.json, package.json, src/components/Tree/Tree.js, src/components/Tree/Tree.module.scss, src/components/Tree/Tree.stories.js, src/components/Tree/VirtualizedTreeList/VirtualizedTreeList.js, src/components/Tree/VirtualizedTreeList/VirtualizedTreeList.module.scss, src/components/Tree/VirtualizedTreeList/index.js, src/components/Tree/useFlattenTreeData/useFlattenTreeData.js, src/components/Tree/utils/index.js
=> BTTRIBEV2-11239-Added virtualized list to tree

package-lock.json, package.json, src/components/Tree/EmptyTreeSearch/EmptyTreeSearch.js, src/components/Tree/EmptyTreeSearch/EmptyTreeSearch.module.scss, src/components/Tree/EmptyTreeSearch/index.js, src/components/Tree/Tree.js, src/components/Tree/Tree.module.scss, src/components/Tree/useTreeVisibleData/useTreeVisibleData.js, src/components/Tree/utils/index.js, src/services/language/languages/en.lang.json
=> BTTRIBEV2-11252 no results indication

src/components/RangeSlider/DualThumb/DualThumb.js
=> add on mouse up

src/components/Tree/Tree.js, src/components/Tree/Tree.stories.js, src/components/Tree/VirtualizedTreeList/VirtualizedTreeList.js, src/components/Tree/useFlattenTreeData/useFlattenTreeData.js, src/components/Tree/useTreeVisibleData/useTreeVisibleData.js, src/components/Tree/utils/index.js
=> Bttribev2 11347 customized keys and allow to add more nodes when state is internally setted

src/components/Tree/Tree.js, src/components/Tree/Tree.stories.js, src/components/Tree/VirtualizedTreeList/VirtualizedTreeList.js, src/components/Tree/useTreeVisibleData/useTreeVisibleData.js, src/components/Tree/utils/index.js
=> tree instance

src/components/Tree/Tree.js, src/components/Tree/Tree.module.scss, src/components/Tree/Tree.stories.js, src/components/Tree/VirtualizedTreeList/VirtualizedTreeList.js, src/components/Tree/useFlattenTreeData/useFlattenTreeData.js, src/storybook/index.module.scss
=> Added tooltip, fixed the height of tree and more small changes

package-lock.json, package.json, src/components/Tree/RootNode/RootNode.module.scss, src/components/Tree/Tree.js, src/components/Tree/Tree.module.scss, src/components/Tree/Tree.stories.js, src/components/Tree/TreeSkeletonLoading/TreeSkeletonLoading.js, src/components/Tree/TreeSkeletonLoading/TreeSkeletonLoading.module.scss, src/components/Tree/TreeSkeletonLoading/index.js, src/components/Tree/VirtualizedTreeList/VirtualizedTreeList.js, src/components/Tree/useTreeVisibleData/useTreeVisibleData.js, src/components/Tree/utils/index.js, src/storybook/Colors/Colors.module.scss, src/storybook/Colors/Colors.stories.js
=> BTTRIBEV2-11237 | Tree Background and TreeSkeletonLoading

src/components/FileUpload/FileUpload.js
=> upload folder enabled

src/components/FileUpload/FileUpload.js
=> add directory

src/components/Table/UseTableReducer/UseTableReducer.js
=> updated the table to ignore disabled rows on mass selection

CHANGELOG.md, src/components/Button/Button.js, src/components/Button/Button.module.scss, src/components/Button/Button.stories.js, src/components/Spinner/Spinner.js, src/components/Spinner/Spinner.module.scss, src/components/Spinner/Spinner.stories.js, src/components/Spinner/index.js, src/index.js, src/storybook/index.module.scss
=> BTTRIBEV2-11578: ADD spinner component

src/components/Button/Button.js, src/components/Spinner/index.js
=> BTTRIBEV2-11578: FIX imports

src/components/Tree/Tree.module.scss, src/components/Tree/useFlattenTreeData/useFlattenTreeData.js
=> Assign isSelectedKeysUpdatedAfterMount after keys are selected

package.json, src/components/Spinner/Spinner.js
=> BTTRIBEV2-11578: Fix build

src/components/Tree/Tree.js, src/components/Tree/Tree.module.scss, src/components/Tree/Tree.stories.js, src/components/Tree/VirtualizedTreeList/VirtualizedTreeList.js, src/components/Tree/useFlattenTreeData/useFlattenTreeData.js, src/components/Tree/useTreeVisibleData/useTreeVisibleData.js, src/components/Tree/utils/index.js
=> APP-11945 allow the tree to have children with same unique ids

src/components/DateTimePicker/DateTimePicker.js
=> add   isNullValue: false

src/components/RangeSlider/RangeSlider.js, src/components/RangeSlider/RangeSlider.stories.js, src/services/language/languages/en.lang.json, src/utils/date.js
=> add duration mode to the dateRange component with storybook example

src/components/RangeSlider/RangeSlider.js, src/components/RangeSlider/RangeSlider.stories.js
=> resolved issues

package-lock.json, package.json, src/components/Dropdown/Dropdown.js, src/components/Dropdown/Dropdown.module.scss
=> APP-12093- changed ui issues in dropdown

src/components/DateTimePicker/DateTimePicker.js
=> date picker inheirt value from parent issues resolved

src/components/Dropdown/Dropdown.js, src/hooks/UseIsOverflowing/UseIsOverflowing.js
=> Added tooltip

src/components/Dropdown/Dropdown.module.scss, src/components/Tree/Tree.module.scss
=> /APP-12208-styles-refactor

src/components/DatePicker/DatePicker.js, src/components/DatePicker/DatePicker.module.scss, src/components/DatePicker/DatePicker.test.js, src/components/DatePicker/DateTimeTextField/DateTimeTextField.js, src/components/DatePicker/DateTimeTextField/DateTimeTextField.module.scss, src/components/DatePicker/DateTimeTextField/index.js, src/components/DatePicker/index.js, src/components/DateTimePicker/DateTimePicker.js, src/components/DateTimePicker/DateTimePicker.test.js, src/components/TextField/TextField.js, src/components/TimePicker/TimePicker.js, src/components/TimePicker/TimePicker.test.js, src/components/ToastMessage/ToastMessage.test.js
=> APP-11564+APP-12193 | text field loses focus on date change and added onBlur+onClose

src/components/DatePicker/DatePicker.js, src/components/DatePicker/DateTimeTextField/DateTimeTextField.js, src/components/DateTimePicker/DateTimePicker.js, src/components/TimePicker/TimePicker.js, src/hooks/UseDebounce/UseDebounce.js, src/hooks/UseDebounce/index.js
=> APP-12253 | Added debounce hook, and applied it in pickers

src/components/Table/TableHeader/TableHeader.js, src/components/Table/UseTableData/useTableData.js
=> APP-11712 | Added filter function to allow custom filter for each column

package-lock.json, package.json
=> Update version manually

src/components/DatePicker/DatePicker.js, src/components/DatePicker/DateTimeTextField/DateTimeTextField.js, src/components/DateTimePicker/DateTimePicker.js, src/components/TextField/TextField.js, src/components/TimePicker/TimePicker.js
=> APP-12309 Placeholder for date/time pickers

src/components/Dropdown/Dropdown.js, src/components/Dropdown/Dropdown.module.scss
=> APP-12314- allow menu height to be flexible

CHANGELOG.md, src/components/StaticInfoTable/StaticInfoTable.js, src/components/StaticInfoTable/StaticInfoTable.module.scss, src/components/StaticInfoTable/StaticInfoTable.stories.js, src/components/StaticInfoTable/StaticInfoTableBody/StaticInfoTableBody.js, src/components/StaticInfoTable/StaticInfoTableBody/StaticInfoTableBody.module.scss, src/components/StaticInfoTable/StaticInfoTableBody/StaticInfoTableList/StaticInfoTableList.js, src/components/StaticInfoTable/StaticInfoTableBody/StaticInfoTableList/StaticInfoTableList.module.scss, src/components/StaticInfoTable/StaticInfoTableBody/StaticInfoTableList/index.js, src/components/StaticInfoTable/StaticInfoTableBody/StaticInfoTableRow/StaticInfoTableRow.js, src/components/StaticInfoTable/StaticInfoTableBody/StaticInfoTableRow/StaticInfoTableRow.module.scss, src/components/StaticInfoTable/StaticInfoTableBody/StaticInfoTableRow/index.js, src/components/StaticInfoTable/StaticInfoTableBody/index.js, src/components/StaticInfoTable/StaticInfoTableContext.js, src/components/StaticInfoTable/StaticInfoTableHeader/StaticInfoTableHeader.js, src/components/StaticInfoTable/StaticInfoTableHeader/StaticInfoTableHeader.module.scss, src/components/StaticInfoTable/StaticInfoTableHeader/index.js, src/components/StaticInfoTable/index.js, src/components/StaticInfoTable/useStaticInfoTableReducer/actions.js, src/components/StaticInfoTable/useStaticInfoTableReducer/index.js, src/components/StaticInfoTable/useStaticInfoTableReducer/useStaticInfoTableReducer.js, src/index.js, src/storybook/index.module.scss
=> APP-11636-static-info-table-initial-strucutre

src/components/Table/TableHeader/TableHeader.js, src/services/language/languages/en.lang.json
=> APP-12288-- added title tag to column management

src/components/Dropdown/Dropdown.js
=> Added auto height prop to Dropdown

src/components/Tree/Tree.js, src/components/Tree/useFlattenTreeData/useFlattenTreeData.js
=> APP-12340- Reset selected keys when the selected keys array is reset from outside

src/components/Dropdown/Dropdown.js, src/components/StaticInfoTable/StaticInfoTable.stories.js, src/components/StaticInfoTable/StaticInfoTableBody/StaticInfoTableBody.js, src/components/StaticInfoTable/StaticInfoTableBody/StaticInfoTableRow/StaticInfoTableRow.js, src/components/StaticInfoTable/StaticInfoTableBody/StaticInfoTableRow/StaticInfoTableRow.module.scss, src/components/StaticInfoTable/StaticInfoTableHeader/StaticInfoTableHeader.js, src/components/StaticInfoTable/StaticInfoTableHeader/StaticInfoTableHeader.module.scss
=> APP-12380- added custom bottom row, necessary for 'call to action' tables

src/components/StaticInfoTable/StaticInfoTableBody/StaticInfoTableRow/StaticInfoTableRow.module.scss, src/components/StaticInfoTable/StaticInfoTableHeader/StaticInfoTableHeader.module.scss
=> Changed colors

src/components/Dialog/Dialog.js
=> Dialog: Add id prop

src/components/Table/Selection/Selection.js
=> INSTALLWIZ-26- Allow selection bar to be hidden

src/components/Table/Selection/Selection.js
=> Added use imperative handle to get access to items from outside

src/components/Tree/Tree.js
=> APP-12516- Removed deps in useEffect

src/components/Tree/useTreeVisibleData/useTreeVisibleData.js
=> APP-12557-changed to includes

src/components/Progress/Progress.js, src/components/Table/UseTableReducer/UseTableReducer.js
=> Added classname to loader

src/components/Dropdown/Dropdown.js
=> APP-11248-Added onMouseDown to open menu

src/components/Dropdown/Dropdown.js
=> APP-12535: Dropdown - add onSearch function

src/components/Autocomplete/Autocomplete.js, src/hooks/UseComponentTranslation/useComponentTranslation.tsx
=> Autocomplete: add translations 

package-lock.json, src/components/Dropdown/Dropdown.stories.js
=> APP-12508 -added story of without-serach to Dropdown

src/components/DateRangePicker/DateRangePicker.js
=> APP-11135: fix date range picker with gap prop

src/components/Dropdown/Dropdown.js, src/components/Dropdown/Dropdown.module.scss, src/components/Dropdown/Dropdown.stories.js, src/components/Dropdown/Dropdown.test.js
=> updated dropdown component with error state and texthelper

src/components/Table/Selection/Selection.js
=> Add bulk element selection table

package-lock.json, src/components/Tooltip/Tooltip.js
=> add showAlways to tooltip

src/components/InputBase/InputBase.js, src/components/InputBase/InputBase.module.scss, src/components/InputBase/InputBase.stories.js, src/components/TextField/TextField.js, src/components/Tree/Tree.js
=> APP-12228- clear text icon for input base

package-lock.json, package.json, src/components/Table/Selection/Selection.module.scss
=> change to ac-floating-blue

src/components/Table/TableBody/TableBody.js
=> Added onTableDateChanged

src/components/Table/Selection/Selection.module.scss
=> remove blue-float

src/components/Dropdown/Dropdown.js
=> APP-13469- Added message ref, so message can be focused when there is an error

CHANGELOG.md
=> test jenkins build

rollup.config.js
=> Build with cjs format

src/components/Menu/Menu.js
=> Add imperativeHandler to know whether menu is open or not and containterClassName

src/components/SelectionGroup/SelectionGroup.js
=> Fix SelectionGroup value when its falsy

src/components/Tree/Tree.js, src/components/Tree/utils/index.js
=> isReturnWholeNodeDataWhenOnSelect tree prop

package-lock.json, package.json
=> updated icons package

src/components/DynamicFilter/DynamicFilter.module.scss, src/components/DynamicFilter/components/DynamicFilterDateTime/DynamicFilterDateTime.module.scss, src/components/DynamicFilter/components/DynamicFilterDateTime/DynamicFilterDateTime.tsx, src/components/DynamicFilter/components/DynamicFilterDateTime/components/DynamicFilterDateTimeDuration.tsx, src/components/DynamicFilter/components/DynamicFilterListFilter/DynamicFilterListFilter.module.scss, src/components/DynamicFilter/components/DynamicFilterListFilter/DynamicFilterListFilter.test.tsx, src/components/DynamicFilter/components/DynamicFilterListFilter/DynamicFilterListFilter.tsx, src/components/DynamicFilter/components/DynamicFilterListFilter/components/FilterList/FilterList.module.scss, src/components/DynamicFilter/components/DynamicFilterListFilter/components/FilterList/FilterList.tsx, src/components/DynamicFilter/components/DynamicFilterMenu/DynamicFilterMenu.module.scss, src/components/DynamicFilter/components/DynamicFilterSelection/DynamicFilterSelection.test.tsx, src/components/DynamicFilter/components/DynamicFilterSlider/DynamicFilterSlider.module.scss, src/components/DynamicFilter/components/DynamicFilterSlider/DynamicFilterSlider.test.tsx, src/components/DynamicFilter/components/DynamicFilterSort/DynamicFilterSort.test.tsx, src/components/MenuSelect/MenuSelect.tsx
=> fix tests and fit to webui

src/components/InfiniteList/InfiniteList.js, src/components/Table/Table.js, src/components/Table/Table.test.js, src/components/Table/TableBody/TableBody.js, src/components/Table/TableBody/TableRow/TableRow.js, src/components/Table/TableBody/TableRow/TableRow.module.scss, src/components/Table/TableHeader/TableHeader.js, src/components/Table/TableHeader/TableHeader.module.scss, src/components/Table/UseTableReducer/UseTableReducer.js, src/components/Table/UseTableReducer/actions.js, src/components/Table/stories/Basic.stories.js
=> expand rows

src/components/DynamicFilter/components/DynamicFilterMenu/DynamicFilterMenu.tsx
=> change default

src/components/DynamicFilter/components/DynamicFilterListFilter/DynamicFilterListFilter.module.scss, src/components/DynamicFilter/components/DynamicFilterListFilter/DynamicFilterListFilter.tsx
=> change to menuSelet on list

src/components/Dropdown/Dropdown.js
=> isUpdateOptionsOnOptionsContent

src/components/DynamicFilter/components/DynamicFilterListFilter/DynamicFilterListFilter.tsx
=> add defaultSearchValue and defaultFilterValue

src/components/DynamicFilter/components/DynamicFilterListFilter/DynamicFilterListFilter.tsx
=> depends of the prev

src/components/Accordion/Accordion.js
=> Accordion: fix expand all prop

package.json, src/components/DynamicFilter/components/DynamicFilterListFilter/components/FilterList/FilterList.module.scss
=> Dynamic filter fix no data list position

src/components/DynamicFilter/DynamicFilter.jsx, src/components/DynamicFilter/stories/Basic.stories.js
=> onClose only on cancel + add BG to story

src/components/DynamicFilter/components/DynamicFilterListFilter/DynamicFilterListFilter.test.tsx, src/components/DynamicFilter/components/DynamicFilterListFilter/DynamicFilterListFilter.tsx, src/components/DynamicFilter/stories/Basic.stories.js, src/components/DynamicFilter/utils.ts
=> Deafult items dynamic filters

src/components/DynamicFilter/components/DynamicFilterListFilter/DynamicFilterListFilter.tsx, src/components/DynamicFilter/stories/Basic.stories.js, src/components/DynamicFilter/utils.ts
=> change to array of ids

package-lock.json, src/components/Dropdown/Dropdown.js, src/components/Dropdown/Dropdown.module.scss, src/components/Dropdown/Dropdown.stories.js, src/components/Dropdown/DropdownItem/DropdownItem.js, src/hooks/UseComponentTranslation/useComponentTranslation.tsx, src/storybook/dropdown.module.scss
=> APP-14496- dropdown add pagination and select all none

src/components/Table/TableBody/TableBody.js, src/components/Table/TableBody/TableRow/TableRow.js, src/components/Table/TableBody/TableRow/TableRow.module.scss
=> add className option + border

src/components/DynamicFilter/DynamicFilter.jsx, src/components/DynamicFilter/DynamicFilter.module.scss
=> APP-14627- filter icon

src/components/DynamicFilter/DynamicFilter.jsx
=> only on handleCancelClick

src/components/DynamicFilter/DynamicFilter.jsx, src/components/DynamicFilter/DynamicFilter.module.scss
=> APP-14627- Added disabled for filter

src/components/Table/TableBody/TableBody.js
=> expand row also on row click

src/components/Checkbox/Checkbox.module.scss, src/components/Tree/Tree.js, src/components/Tree/Tree.stories.js, src/components/Tree/VirtualizedTreeList/VirtualizedTreeList.js, src/storybook/tree.module.scss
=> APP-14727- Custom style for tree nodes and dynamic heights

src/components/Accordion/Accordion.js
=> APP-14763: Accordion - fix expandAll prop 

src/components/Table/TableBody/TableRow/TableRow.module.scss
=> change arrow direction

package-lock.json, package.json
=> APP-14763: Update version to 219

package-lock.json, package.json, src/components/Tree/Tree.js, src/components/Tree/Tree.stories.js, src/components/Tree/Tree.test.js, src/components/Tree/VirtualizedTreeList/VirtualizedTreeList.js, src/components/Tree/useFlattenTreeData/useFlattenTreeData.js, src/components/Tree/useTreeVisibleData/useTreeVisibleData.js, src/components/Tree/utils/index.js, src/storybook/tree.module.scss
=> APP-14735- on expand to load more children controlled from outside

src/components/Tree/VirtualizedTreeList/VirtualizedTreeList.js, src/components/Tree/utils/index.js
=> Fixed view in list

src/components/InfiniteList/InfiniteList.js
=> Added otherProps to inifintieList to allow to add another props from outside to react-windows' List props

src/components/Tree/Tree.js, src/components/Tree/Tree.module.scss, src/components/Tree/Tree.stories.js, src/components/Tree/useFlattenTreeData/useFlattenTreeData.js, src/components/Tree/useNodeSelectionWithExclusion/useNodeSelectionWithExclusion.js
=> APP-14604- Handle default initial selection of tree when controlled from outside

src/components/Tree/VirtualizedTreeList/VirtualizedTreeList.js, src/components/Tree/VirtualizedTreeList/VirtualizedTreeList.module.scss, src/components/Tree/useTreeVisibleData/useTreeVisibleData.js
=> APP-14850- Fix data overriding of state

src/components/Autocomplete/Autocomplete.js, src/components/Autocomplete/Autocomplete.test.js, src/components/Dropdown/Dropdown.js, src/components/Dropdown/Dropdown.test.js, src/utils/index.js
=> APP-14981- Fixed menu position top/bottom by adding usePopper and remove unnecessary code

src/components/DynamicFilter/DynamicFilter.jsx, src/components/DynamicFilter/DynamicFilter.module.scss, src/hooks/UseIsOverflowing/UseIsOverflowing.js
=> APP-15048- Added tooltip with useIsoverflowing hook to listen window resize in case label is overflown

src/components/Table/TableBody/TableBody.js
=> Optional chaining to row click callback

src/components/Tooltip/Tooltip.js
=> CORE-5535 - Added custom class to tooltip arrow

src/components/Tree/utils/index.js
=> Fixed selection of parent node without children

package-lock.json, package.json
=> Update version to 1.0.0-beta.231

package-lock.json, package.json
=> Update version to 1.0.0-beta.232

src/components/Tree/Tree.js, src/components/Tree/useFlattenTreeData/useFlattenTreeData.js, src/components/Tree/useNodeSelectionWithExclusion/useNodeSelectionWithExclusion.js, src/components/Tree/utils/index.js
=> APP-15761-Calculate direct children of a node only, without the indirect descendents and getParentExcludeMode

src/components/Tree/utils/index.js
=> APP-15761- Fix calculation of totalSelected parent nodes when parent child has the same selection as parent exclude mode

src/components/Tree/Tree.js, src/components/Tree/utils/index.js
=> APP-15497: Tree -add function to generate new data structure after d&d

src/components/Tree/Tree.js, src/components/Tree/VirtualizedTreeList/VirtualizedTreeList.js
=> APP-15832: Tree - add isDraggable prop

src/components/Tree/Tree.js, src/components/Tree/Tree.module.scss, src/components/Tree/Tree.stories.js, src/components/Tree/Tree.test.js, src/storybook/index.module.scss
…Expand props instead of isBulkActions
=> APP-16331: Tree - Fix Styles & Props changes

src/components/Tree/VirtualizedTreeList/VirtualizedTreeList.js
=> APP-15937: disable drag drop for leaf node

src/components/Tree/VirtualizedTreeList/VirtualizedTreeList.js
=> APP-16377: Add root nodes prop to renderParent function

src/components/Tree/Tree.js
=> APP-13677: Add nodesmap

src/components/Tree/Tree.js
=> add nodesmap

src/components/Tree/Tree.js
=> APP-15928: Tree component - Add full node object on select click

src/components/Tree/Tree.js
=> APP-15928: Tree component - Add scrollToItem function

src/components/Tree/Tree.js
=> APP-15928: Add treeInstance to dependency list

src/components/DatePicker/DatePicker.js
=> Added useEffect to DatePicker
